### ISSUE TITLE
FileNotFoundException with war --nrepl-start without cider-nrepl?

### ISSUE THREAD

**Issue by terjesb** [immutant/lein-immutant#110]
I'm porting a couple of simple services from Immutant 1 on JBoss AS to Immutant 2 on WildFly 9 CR2. Seems pretty straightforward, so that's nice!

With Immutant 1, nrepl for an .ima was started implicitly via an [:immutant :nrepl-port] key in project.clj.

With Immutant 2 I found that I need to use [:immutant :war :nrepl :port] and then lein immutant war --nrepl-start to get the same behavior. The Migration guide didn't mention this or anything about nrepl, I think, maybe a short note about it should be added.

During deploy, I the got the error below -- FileNotFound on some cider-nrepl stuff. (It seemed that the WAR got deployed even with this error.)

Adding cider/cider-nrepl to my project.clj fixes the problem.

Is it expected that cider-nrepl is required for the nrepl server to start, or should I be able to have nrepl without this plugin?

```
2015-06-20 15:00:19,722 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 93) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./XXX: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./legacy-jobs: java.lang.RuntimeException: java.lang.RuntimeException: Initialization failed
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Initialization failed
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:224)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
        ... 6 more
Caused by: java.lang.RuntimeException: Initialization failed
        at org.projectodd.wunderboss.wildfly.ServletListener.contextInitialized(ServletListener.java:100)
        at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:173)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:195)
        ... 8 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: Could not locate cider/nrepl/middleware/apropos__init.class or cider/nrepl/middleware/apropos.clj on classpath.
        at org.projectodd.wunderboss.clojure.ClojureLanguage.eval(ClojureLanguage.java:74)
        at org.projectodd.wunderboss.ApplicationRunner.start(ApplicationRunner.java:52)
        at org.projectodd.wunderboss.wildfly.ServletListener$2.call(ServletListener.java:75)
        at org.projectodd.wunderboss.wildfly.ServletListener$2.call(ServletListener.java:72)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: Could not locate cider/nrepl/middleware/apropos__init.class or cider/nrepl/middleware/apropos.clj on classpath.
        at org.projectodd.wunderboss.LoaderWrapper.callInLoader(LoaderWrapper.java:35)
        at org.projectodd.wunderboss.clojure.ClojureLanguage.eval(ClojureLanguage.java:65)
        ... 7 more
Caused by: java.io.FileNotFoundException: Could not locate cider/nrepl/middleware/apropos__init.class or cider/nrepl/middleware/apropos.clj on classpath.
        at clojure.lang.RT.load(RT.java:449)
        at clojure.lang.RT.load(RT.java:412)
        at clojure.core$load$fn__5448.invoke(core.clj:5866)
        at clojure.core$load.doInvoke(core.clj:5865)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5671)
        at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
        at clojure.core$load_lib.doInvoke(core.clj:5710)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:632)
        at clojure.core$load_libs.doInvoke(core.clj:5749)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:632)
        at clojure.core$require.doInvoke(core.clj:5832)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at immutant.internal.util$require_resolve.invoke(util.clj:54)
        at immutant.wildfly.repl$start$fn__951.invoke(repl.clj:61)
        at clojure.core$map$fn__4553.invoke(core.clj:2622)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:507)
        at clojure.core$seq__4128.invoke(core.clj:137)
        at clojure.core$apply.invoke(core.clj:630)
        at immutant.wildfly.repl$start.invoke(repl.clj:63)
        at clojure.lang.Var.invoke(Var.java:379)
        at immutant.wildfly$init_deployment.invoke(wildfly.clj:90)
        at clojure.core$eval42.invoke(NO_SOURCE_FILE:0)
        at clojure.lang.Compiler.eval(Compiler.java:6782)
        at clojure.lang.Compiler.eval(Compiler.java:6772)
        at clojure.lang.Compiler.eval(Compiler.java:6772)
        at clojure.lang.Compiler.eval(Compiler.java:6745)
        at clojure.core$eval.invoke(core.clj:3081)
        at clojure.lang.Var.invoke(Var.java:379)
        at org.projectodd.wunderboss.clojure.ClojureLanguage$2.call(ClojureLanguage.java:69)
        at org.projectodd.wunderboss.LoaderWrapper.callInLoader(LoaderWrapper.java:33)
        ... 8 more

2015-06-20 15:00:19,739 ERROR [org.jboss.as.controller.management-operation] (DeploymentScanner-threads - 1) WFLYCTL0013: Operation ("full-replace-deployment") failed - address: ([]) - failure description: {"WFLYCTL0080: Failed services"
=> {"jboss.undertow.deployment.default-server.default-host./legacy-jobs" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./legacy-jobs: java.lang.RuntimeException: java.lang.Runtime
Exception: Initialization failed
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Initialization failed
    Caused by: java.lang.RuntimeException: Initialization failed
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: Could not locate cider/nrepl/middleware/apropos__init.class or cider/nrepl/middleware/apropos.clj on classpath.
    Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: Could not locate cider/nrepl/middleware/apropos__init.class or cider/nrepl/middleware/apropos.clj on classpath.
    Caused by: java.io.FileNotFoundException: Could not locate cider/nrepl/middleware/apropos__init.class or cider/nrepl/middleware/apropos.clj on classpath."}}
```

**Comment by tobias** [comment]
On Sat, Jun 20, 2015 at 11:41 AM, Terje <notifications@github.com> wrote:

> With Immutant 2 I found that I need to use [:immutant :war :nrepl :port]
> and then lein immutant war --nrepl-start to get the same behavior. The
> Migration guide didn't mention this or anything about nrepl, I think, maybe
> a short note about it should be added.


You're right - we need to discuss nrepl options in the migration guide -
I've added an issue for that: https://issues.jboss.org/browse/IMMUTANT-566

With 2.x, we now have a "dev" war option that will give you an nrepl
automatically, but the produced war doesn't include the app source or
dependencies, it just points to them in the project dir and ~/.m2/,
respectively. The plugin acquires the classpath from lein, which includes
nrepl and any nrepl middeware jars.

> During deploy, I the got the error below -- FileNotFound on some
> cider-nrepl stuff. (It seemed that the WAR got deployed even with this
> error.)
>
If nrepl is active, the war creation captures the currently-active nrepl
options (which may include cider-nrepl), and will apply those options when
starting nrepl in the container. For a dev war, the cider-nrepl jar will be
available because it will be on the project classpath provided by lein. For
a non-dev war, it does need to be added manually.


> Is it expected that cider-nrepl is required for the nrepl server to start,
> or should I be able to have nrepl without this plugin?
>
>
If you want a nrepl server that doesn't try to load cider-nrepl, you need
to exclude the plugin with a profile and have that profile active when
creating the jar.

If you only need nrepl in wars that you are using locally, a "dev" war
(`lein immutant war --dev`) may be a better option.

**Comment by terjesb** [comment]
Excellent, thank you.
